services:
    backend:
        build: ./flask
        stop_signal: SIGINT
        volumes:
            - ./flask:/src
        environment:
            - FLASK_SERVER_PORT=80
        ports:
            - 80:80
        depends_on:
            - mongo
    
    mongo:
        image: mongo